/run/verbose 0
/event/verbose 0
/tracking/verbose 0

#/process/em/fluo true
#/process/em/auger true
#/process/em/pixe true

/run/initialize
/process/had/rdm/thresholdForVeryLongDecayTime 434 year
/ns/gun/particle alpha

/ns/gun/energy 5.486 MeV
/ns/gun/position 0 0 0 cm
/ns/gun/direction 0 0 -1 

#volume
#/ns/gun/type Volume
#/ns/gun/shape Cylinder
#/ns/gun/center 0. 0. -3.49995 mm
#/ns/gun/radius 3 mm
#/ns/gun/halfz  0.00005 mm
#/ns/gun/confine Pellet

/run/beamOn 1000000



